---

language: golang

go:
  - 1.14.x
sudo: required
services:
  - docker

before_script:
  - source build/set_env.sh

script:
  - docker build -t terraform-pipeline .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag terraform-pipeline corberos/terraform-pipeline:latest
  - docker tag terraform-pipeline corberos/terraform-pipeline:$DOCKER_BUILD_VERSION
  - docker push corberos/terraform-pipeline:latest
  - docker push corberos/terraform-pipeline:$DOCKER_BUILD_VERSION

env:
  - DOCKER_BUILD_VERSION=$(cat VERSION)